---
- name: add the official Sensu repository's key
  apt_key: url=https://repos.sensuapp.org/apt/pubkey.gpg state=present

- name: add the official Sensu repository
  copy:
    src=sensu-server.list
    dest=/etc/apt/sources.list.d/
    backup=yes
  register: aptrepo

- name: refresh apt cache
  apt: update_cache=yes
  when: aptrepo.changed

- name: install sensu
  apt: name=sensu state=present

- name: enable sensu-client to survive reboot
  service: name=sensu-client enabled=yes

- name: create the SSL directory
  file:
    path=/etc/sensu/ssl
    owner=sensu
    group=sensu
    mode=0750
    state=directory

- name: copy the SSL certificates
  copy:
    src=files/sensu_{{ item }}.pem
    dest=/etc/sensu/ssl/{{ item }}.pem
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  with_items:
    - client_cert
    - client_key

- name: generate /etc/sensu/config.json
  template:
    src=sensu.client.config.json.j2
    dest=/etc/sensu/conf.d/client.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify: restart sensu client daemons

- name: copy all the checks files
  copy:
    src=files/sensu/plugins/
    dest=/etc/sensu/plugins/
    owner=sensu
    group=sensu
    mode=0750
  notify: restart sensu client daemons
